### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by jamesriady** [Pyrolistical/microapps#2]
I have done `npm install` then I run `npm run dev` but I got error `webpack: failed to  compile`

**Comment by Pyrolistical** [comment]
`npm install`, then `npm start`

**Comment by jamesriady** [comment]
@Pyrolistical I `cd` into 1 by 1 project but it occurs error because all project has the same port.. how to split the port?

**Comment by Pyrolistical** [comment]
don't use this project then. the whole point of this project is to show how all these different apps run on the same webserver, ie port

**Comment by jamesriady** [comment]
do you mean that if I only cd into microapps' folder, then `npm install` and `npm start`, all the project will start too in the same port?
